services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service
    ports:
      - "3307:3306"

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
    - discovery-server

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - inventory-service
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - discovery-server
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product-service
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
