# spring.application.name=order-service

# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/order_service}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# spring.datasource.hikari.initialization-fail-timeout=60000
# spring.datasource.hikari.connection-timeout=60000

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# eureka.client.service-url.defaultZone=${EUREKA_URL:http://discovery-server:8761/eureka}

# server.port=8081

# management.health.circuitbreakers.enabled=true
# management.endpoints.web.exposure.include=*

# resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
# resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
# resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50 
# resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s

# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer 
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# spring.kafka.bootstrap-servers=${KAFKA_URL:broker:29092}

# spring.kafka.producer.properties.spring.json.add.type.headers=false


spring.application.name=order-service

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

eureka.instance.prefer-ip-address=true

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.inventory.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventory.slidingWindowSize=5
resilience4j.circuitbreaker.instances.inventory.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventory.waitDurationInOpenState=5s

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false
